### ISSUE TITLE
AP disabled/unavailable when entering incorrect SSID

### ISSUE THREAD

**Issue by tripflex** [mongoose-os-apps/wifi-setup-web#3]
If you enter in an incorrect SSID (meaning it can't connect), the AP gets completely disabled and there's no way to connect back to the device to configure the correct settings ... this is a show stopper.

This is what console shows over and over again, even after timeout it still continues to try to connect ....

```shell
[May 19 14:59:59.429] esp32_wifi_ev        Disconnected from Devicesz, reason: 201
[May 19 14:59:59.587] mgos_net_on_change_c WiFi STA: disconnected
[May 19 14:59:59.642] mgos_net_on_change_c WiFi STA: connecting
[May 19 15:00:02.427] esp32_wifi_ev        Disconnected from Devicesz, reason: 201
[May 19 15:00:02.588] mgos_net_on_change_c WiFi STA: disconnected
[May 19 15:00:02.643] mgos_net_on_change_c WiFi STA: connecting
[May 19 15:00:03.222] mgos_wifi_sta_connec WiFi STA: Connect timeout
[May 19 15:00:03.230] mgos_wifi_get_next_s WiFi STA: Using config 0
```

Further testing on this it appears when initially setting wrong SSID, the AP goes down for around ~1-2 minutes before coming back up ... random the amount of time each test I do, only does this on initial clean firmware and set wrong SSID

**Comment by mamuesp** [comment]
My suggestion: count how often the device tries to reconnect, and after a certain amount (you will like to configure that), you write someting like
`Cfg.set( { wifi: { ap: { enable: true }, sta: { enable: false }, sta1: { enable: false }, sta2: { enable: false } } });`(JavaScript version) to the configuration and reboot - et voilà - the AP is as good as before. 

Thats my solution I implemented, and it works fine. So why has this to be in the OS? This is no issue at all in my opinion. Consider that every functionality that will be added will blow up the used space.

**Comment by cpq** [comment]
Go fix it.

**Comment by blasco** [comment]
@mamuesp It is an issue, both AP and STA should work regardeless of setting a correct or wrong ssid. I've solved it doing something similar to what you did, but it's a pitty that such core functionallity needs such a cheap walkaround...

**Comment by tripflex** [comment]
@mamuesp well, I took that idea and ran with it, and created a library "Provision WiFi", check it out here when you get a chance:
https://github.com/tripflex/mos-lib-provision-wifi

After going through the WiFi lib for days on end (to build out my lib), I think the issue comes down to this not necessarily being an issue with this example app, but more on the side of how wifi is handled ( I was trying to use this example app to build out a lib like a "captive portal") and was having the AP disconnect issues due to device rebooting

**Comment by blasco** [comment]
Yes, I've oppened an issue in the wifi library. You are right, this is not realted to this library. Have a nice day
